name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: leetcode-notes

      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: GaryHo34/leetcode-site
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0 
          path: leetcode-sites

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./leetcode-sites
        run: yarn install

      - name: Build docs
        working-directory: ./leetcode-sites/script
        run: sh build.sh

      - name: Build website
        working-directory: ./leetcode-sites
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./leetcode-sites/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4